# -*- coding: utf-8 -*-
"""
Bad words

"""

nouns = [
    '4r5e',
    '5h1t',
    '5hit',
    'a55',
    'anus',
    'ar5e',
    # 'arrse',
    'arse',
    'ass',
    'ass-fucker',
    'asses',
    'assfucker',
    'assfukka',
    'asshole',
    'assholes',
    # 'asswhole',
    # 'a_s_s',
    'b!tch',
    'b00bs',
    'b17ch',
    'b1tch',
    'ballbag',
    'balls',
    'ballsack',
    'bastard',
    'bellend',
    'biatch',
    'bitch',
    'bitcher',
    'bitches',
    'bollock',
    'boner',
    'boob',
    'boobs',
    'breasts',
    'buceta',
    'bum',
    'bunny fucker',
    'butt',
    'butthole',
    'buttmuch',
    'buttplug',
    'c0ck',
    'c0cksucker',
    'carpet muncher',
    'cawk',
    'clit',
    'clitoris',
    'cock',
    'cock-sucker',
    'cockface',
    'cockhead',
    'cockmunch',
    'cockmuncher',
    'crap',
    'cummer',
    'cumshot',
    'cunt',
    'cuntlicker',
    'cyberfucker',
    'd1ck',
    'dick',
    'dickhead',
    'dildo',
    'dink',
    'donkeyribber',
    'doosh',
    'duche',
    'dyke',
    'ejaculation',
    'fanny',
    'fannyfucker',
    'fatass',
    'felcher',
    'fingerfucker',
    'fistfucker',
    'fuck',
    'fucker',
    'fuckhead',
    'fuckwhit',
    'knob',
    'knobend',
    'knobhead',
    'knobjockey',
    'labia',
    'm0f0',
    'mothafucka',
    'mothafucker',
    'mother dick',
    'mother fucker',
    'motherfucker',
    'muff',
    'nazi',
    'numbnuts',
    'nutsack',
    'pecker',
    'penis',
    'penisfucker',
    'pigfucker',
    'pisser',
    'prick',
    'pube',
    'pussy',
    'rectum',
    'retard',
    'schlong',
    'scroat',
    'scrotum',
    'shagger',
    'shemale',
    'shit dick',
    'shitfuck',
    'shithead',
    'shitter',
    'skank',
    'slut',
    'smegma',
    'snatch',
    'son-of-a-bitch',
    'spunk',
    'testical',
    'testicle',
    'tit',
    'tittiefucker',
    'tosser',
    'turd',
    'tw4t',
    'twat',
    'twathead',
    'vagina',
    'vulva',
    'wang',
    'wanker',
    'whore',
]

verbs = [
    'do beastiality',
    'give blow jobs',
    'give blowjobs',
    'bugger',
    'cocksuck',
    'cum',
    'cunilingus',
    'cunt lick',
    'cyberfuck',
    'ejaculate',
    'felch',
    'fellate',
    'finger fuck',
    'fist fuck',
    'fuck',
    'gangbang',
    'have hard core sex',
    'jack-off',
    'jerk-off',
    'jizz',
    'masturbate',
    'watch p0rn',
    'act in p0rn',
    'pay for porn',
    'spend all of their money on phone sex',
    'piss',
    'poop',
    'have a good rimming',
    'take long shits on the beach',
    'tit fuck swine',
    'wank in the park',
]

adjectives = [
    'anal',
    'beastial',
    'bitchin',
    'bitching',
    'bloody',
    'cocksucking',
    'cumming',
    'cuntlicking',
    'cyberfucked',
    'cyberfucking',
    'damn',
    'dog-fucker',
    'doggin',
    'dogging',
    'ejaculating',
    'felching',
    'fingerfucked',
    'fingerfucking',
    'fistfucked',
    'fistfucking',
    'fucked',
    'gangbanged',
    'goddamn',
    'goddamned',
    'horniest',
    'horny',
    'mothafuckin',
    'mothafucking',
    'pig fucking',
    'pissed',
    'shite',
    'shitting',
    'shitty',
    'twatty',
    'wanky',
]
